# Generated by Django 3.0.7 on 2020-06-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DinnerPlatter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('prizeSmall', models.FloatField(max_length=8)),
                ('prizeLarge', models.FloatField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('prize', models.FloatField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Salad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('prize', models.FloatField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('prizeSmall', models.FloatField(max_length=8)),
                ('prizeLarge', models.FloatField(max_length=8)),
            ],
        ),
        migrations.RemoveField(
            model_name='topping',
            name='pizzas',
        ),
        migrations.DeleteModel(
            name='Pizza',
        ),
    ]
