# Generated by Django 3.0.7 on 2020-06-28 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200628_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='dish',
            new_name='dishType',
        ),
    ]
