# Generated by Django 3.0.7 on 2020-06-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200628_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dishType', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('prizeSmall', models.FloatField(blank=True, max_length=8, null=True)),
                ('prizeLarge', models.FloatField(blank=True, max_length=8, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
