# Generated by Django 3.0.7 on 2020-07-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200711_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='post_code',
            field=models.IntegerField(),
        ),
    ]
