# Generated by Django 3.0.7 on 2020-07-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200711_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prize',
            field=models.FloatField(null=True),
        ),
    ]
