# Generated by Django 3.0.7 on 2020-07-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_product_prize'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizzaType', models.CharField(max_length=16)),
                ('size', models.CharField(max_length=16)),
                ('standartPrice', models.FloatField()),
                ('oneTopPrice', models.FloatField()),
                ('twoTopPrice', models.FloatField()),
                ('threeTopPrice', models.FloatField()),
            ],
        ),
    ]
