# Generated by Django 3.0.7 on 2020-07-29 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_pizza_specialprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='prizeLarge',
            new_name='priceLarge',
        ),
        migrations.RenameField(
            model_name='dish',
            old_name='prizeSmall',
            new_name='priceSmall',
        ),
    ]
