# Generated by Django 3.0.7 on 2020-07-29 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20200729_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='extra_information',
            new_name='note',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='prize',
            new_name='price',
        ),
    ]
