# Generated by Django 3.0.7 on 2020-08-01 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20200730_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_entry',
            old_name='order_id',
            new_name='order',
        ),
    ]
