# Generated by Django 3.0.7 on 2020-08-04 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_order_is_sent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_sent',
            new_name='is_delivered',
        ),
    ]
