# Generated by Django 3.0.7 on 2020-08-09 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_delivered',
        ),
    ]
