# Generated by Django 3.0.7 on 2020-08-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_auto_20200809_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PD', 'Pending'), ('IP', 'In Progress'), ('DL', 'Delivering'), ('RC', 'Received')], default='PD', max_length=2),
        ),
    ]
